version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: wallet-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017' # opcional para conectarte desde host
    networks:
      - wallet_net

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: wallet-mailhog
    restart: unless-stopped
    ports:
      - '8025:8025' # UI para ver correos
    networks:
      - wallet_net

  wallet-db:
    build:
      context: ./services/wallet-db
      dockerfile: Dockerfile
    container_name: wallet-db
    restart: unless-stopped
    env_file: .env
    environment:
      # Mongoose connection
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/${MONGO_DB_NAME}?authSource=admin
      MAILHOG_HOST: ${MAILHOG_HOST}
      MAILHOG_PORT: ${MAILHOG_PORT}
      MAIL_FROM: ${MAIL_FROM}
      PORT: ${WALLET_DB_PORT}
    depends_on:
      - mongo
      - mailhog
    ports:
      - '${WALLET_DB_PORT}:${WALLET_DB_PORT}'
    networks:
      - wallet_net

  wallet-api:
    build:
      context: ./services/wallet-api
      dockerfile: Dockerfile
    container_name: wallet-api
    restart: unless-stopped
    env_file: .env
    environment:
      PORT: ${WALLET_API_PORT}
      WALLET_DB_BASE_URL: ${WALLET_DB_BASE_URL}
    depends_on:
      - wallet-db
    ports:
      - '${WALLET_API_PORT}:${WALLET_API_PORT}'
    networks:
      - wallet_net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: wallet-client
    restart: unless-stopped
    env_file: .env
    environment:
      VITE_API_BASE_URL: ${WALLET_API_BASE_URL}
    depends_on:
      - wallet-api
    ports:
      - '${CLIENT_PORT}:80'
    networks:
      - wallet_net

volumes:
  mongo_data:

networks:
  wallet_net:
    driver: bridge
